# Generated by Django 5.0.6 on 2024-07-04 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_remove_customer_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
